[package]
name = "calx"
version = "0.3.0-alpha"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Game programming utilities"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
euclid = "0.17"
image = "0.18"
num = "0.1"

# TODO change to
#     rand = "0.5"
# when it gets a stable release
rand = { git = "https://github.com/rust-lang-nursery/rand" }

serde = "1.0"
serde_derive = "1.0"
tempdir = "0.3"
time = "0.1"
vec_map = "0.8"

[dev-dependencies]
serde_json = "1.0"
